version: "3.8"
 
services:
  api:
    build: .
    container_name: api_server
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
 
  redis:
    image: redis:6.2
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
 
volumes:
  redis_data: